### ISSUE TITLE
Panel going over the screen and bypassing paddings

### ISSUE THREAD

**Issue by Umar-Turdiev** [Ballpits/MotionMagic-Web#1]
**Describe the bug**
Panel going over the screen and bypassing paddings, overflowing out of the screen.

**Expected behavior**
It should hit the padding and become scrollable.

**Comment by Umar-Turdiev** [comment]
@Naungth please branch out from `develop`, and create branch called `fix-panel-overflow`.

**Comment by Naungth** [comment]
sure, I will be developing from this branch

**Comment by Umar-Turdiev** [comment]
Resolved in #2 by @Naungth.

**Comment by Umar-Turdiev** [comment]
Solved in #5.
